version: '3.8'
services:
  app:
    image: animals-app
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/paint
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: paint
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
