name: Spring CI/CD

on:
 push:
    branches:
      - main
    paths:
      - 'ng/**'
      - './ng/**'
      - '../ng/**'

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Change to backend directory
      run: cd ./ng

    - name: Build with Maven
      run: mvn clean package

    - name: Run Tests
      run: mvn test
